import { NotificationType } from '../../application/ports/notification.service.port';

export class Notification {
    constructor(
        public readonly id: string,
        public readonly userId: string,
        public readonly type: NotificationType,
        public readonly message: string,
        public readonly isRead: boolean,
        public readonly createdAt: Date,
        public readonly updatedAt: Date,
    ) { }

    static create(params: {
        userId: string;
        type: NotificationType;
        message: string;
    }): Notification {
        return new Notification(
            '', // ID will be generated by DB
            params.userId,
            params.type,
            params.message,
            false,
            new Date(),
            new Date(),
        );
    }
}
